---
title: "Final Report"
authors: "Jing Lyu, Mengfan Luo, Yushan Wang, Yiqun Jin"
output: 
  html_document
---

## Motivation: 

 It is known that the health insurance companies stratify smokers and non-smokers and assign different insurance prices according to smoking status. Intuitively, we think that as price increase, the smoker would less likely to purchase health insurance.

Since health insurance is vital for people’s well-being, and the cost is the main reason that stops people from buying insurance, we are interested in exploring the relationship between smoking and health insurance. To be specific, our research topic can be divided into three research questions. We would like to investigate if smokers in NYC tend to get insurance, what type of insurance they prefer, and the factors that affect insurance cost. 

Another reason that limits access to insurance is lack of information. As such, mapping of health consulting centers, health insurance carriers locations, and medicaid provider location in NYC, along with their contact information and operation hours, are also provided for readers who need more information for insurance and health advice.


## Related work: 

The [Health Market website](https://www.healthmarkets.com/content/smoking-and-health-insurance) introduced the idea of **tobacco rating**. Tobacco rating is the practice of charging tobacco users more for health insurance. In fact, the charge for smokers can be up to 50% more than non-smokers, which lead us to consider if smokers would be frustrated to purchase insurance. 

In addition, there are many tweets on twitter that discuss the relationship between smoking and health insurance. We have read that smokers lose access to many health resources due to higher cost of insurance, and insurance won't approve as many treatments for smokers as non-smokers.

These facts inspired us to look deep into the relationship between smoking and health insurance.

## Initial questions:

The initial questions we were trying to answer was if smokers in NYC tend to get insurance, what type of insurance they prefer. Over the course of the project, we added a new research question relating to the topic, which was the investigation of factors that affect insurance cost. 

This new question assists our main research topic, because we can use the factors (age, bmi, smoker, etc) to not only explain what kind of personal characteristics would affect insurance cost, but also build a prediction model for health insurance charges. By doing such, we would gain better insights to the underlying relationship between health insurance and smoking, along with other important variables that contributes to the cost variation of insurance.

## Data: 
Source, scraping method, cleaning, etc.

### Data source

#### Datasets for analysis

* [Community Health Survey Public Use Data](https://www1.nyc.gov/site/doh/data/data-sets/community-health-survey-public-use-data.page). This dataset contains survey questions regarding smoking and health insurance. We extracted related questions from the survey for analysis.

* [Medical Cost Personal Dataset](https://www.kaggle.com/mirichoi0218/insurance). This dataset sheds lights on insurance charges for different personal characteristics, such as smoking, age, bmi, region, etc.

#### Datasets for mapping

* [Primary Care Access and Planning - Health Insurance Enrollment](https://data.cityofnewyork.us/Health/Primary-Care-Access-and-Planning-Health-Insurance-/gfej-by6h). This dataset is used for mapping of health consulting centers in NYC. 

* [Medicaid Enrolled Provider Listing](https://health.data.ny.gov/Health/Medicaid-Enrolled-Provider-Listing/keti-qx5t): This dataset is used for mapping of Medicaid provide locations in NYC.

* In addition, locations of major health insurance carriers in NYC is collected manually and used to create interactive mapping of these carriers.

### Data cleaning


## Exploratory analysis: 
Visualizations, summaries, and exploratory statistical analyses. Justify the steps you took, and show any major changes to your ideas.


## Additional analysis: 
If you undertake formal statistical analyses, describe these in detail


## Discussion: 
What were your findings? Are they what you expect? What insights into the data can you make?

