---
title: "Insurance type explain"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r, echo = F}
library(tidyverse)
```

## Table

```{r}
insur_type <- c("Employer", "Medicare", "Milit/CHAMPUS", "Uninsured", "Self-purchased", "Medicaid/Family Health+", "COBRA/other")

insur_meaning <- c("Employer-sponsored health insurance is a health insurance selected and purchased by your employer and offered to eligible employees and their dependents.",
                   "Medicare is federal health insurance for people 65 or older, some younger people with disabilities, people with End-Stage Renal Disease",
                   "Health Care progam for military",
                   "Not insured",
                   "Insurance purchased by individual choice",
                   "Medicaid/health insurance program for adults who are aged 19 to 64 who have income too high to qualify for Medicaid",
                   "Consolidated Omnibus Budget Reconciliation Act, which gives some employees the ability to continue health insurance coverage after leaving employment, or other types of insurance.")

insur <- data.frame(insur_type, insur_meaning) %>% 
  dplyr::rename(
    "Insurance type" = insur_type,
    "Insurance type meaning" = insur_meaning
  )
knitr::kable(insur)
```

## Cite

https://www.medmutual.com/for-individuals-and-families/health-insurance-education/health-insurance-basics/employer-vs-individual-health-insurance.aspx

https://www.medicare.gov/what-medicare-covers/your-medicare-coverage-choices/whats-medicare

https://en.wikipedia.org/wiki/Consolidated_Omnibus_Budget_Reconciliation_Act_of_1985

