---
title: "Project Proposal"
date: "11/10/2021"
output: 
  github_document
---

### Group members:
Yushan Wang(yw3772), Jing Lyu(jl6049), Yiqun Jin(yj2686), Mengfan Luo(ml4701)

### Tentative project title:
Smoker and their health Insurance/recources in NYC

### Motivation for project and intended final products:

* Motivation: 

It is known that smokers have higher price for health insurance than non-smokers. As such, we are interested in exploring if smokers in NYC tend to get insurance, and what type of insurance they prefer.

* Final products:

Correlation between access to health coverage/resources and smoking. 

Factors that affect whether or not a smoker choose to buy insurance, such as self-awareness, access to health resources, and other factors.

Suggestion and mapping on where to get consulting for insurance/health center location.

Aspects:

1. Self-awareness - has insurance, time length of no insurance, told doctor not accepting insurance, where go when sick or need advice(also related with good/bad resources)...

2. Access to health resources - not get insurance when need, not fill a prescription because of cost, can't afford...

3. Other co-variables - general health

### Anticipated data sources

* Community Health Survey Public Use Data - https://www1.nyc.gov/site/doh/data/data-sets/community-health-survey-public-use-data.page
<<<<<<< HEAD

* Primary Care Access and Planning - Health Insurance Enrollment - https://data.cityofnewyork.us/Health/Primary-Care-Access-and-Planning-Health-Insurance-/gfej-by6h

* Facts about cigarette - https://www.medicalnewstoday.com/releases/12481#1 (only facts, not dataset)

### The planned analyses / visualizations / coding challenges

* Analyses:

Analyse relationship between access to health resources and smoking;

Analyse different aspects in relation with whether or not getting insurance.

=======

* Primary Care Access and Planning - Health Insurance Enrollment - https://data.cityofnewyork.us/Health/Primary-Care-Access-and-Planning-Health-Insurance-/gfej-by6h

* Facts about cigarette - https://www.medicalnewstoday.com/releases/12481#1 (only facts, not dataset)

### The planned analyses / visualizations / coding challenges

* Analyses:

Analyse relationship between access to health resources and smoking;

Analyse different aspects in relation with whether or not getting insurance.

>>>>>>> d176472f23174d073fb502384c981192b6be3cc4
(Analyse confounder/biases that contributes the correlation.)


* Visualizations: 

Mapping of NYC health center location where health insurance enrollment and assistance with SNAP benefits are offered (it can be used by general public seeking assistance with signing up for health insurance);

Will think of more visualizations during analysis (use plotly)


* Coding challenges: 

Different survey questions in each years - can not analyse correlation when the data are from different years.
<<<<<<< HEAD

Difficulty of cleaning dataset and extract desired content from a survey;

=======

Difficulty of cleaning dataset and extract desired content from a survey;

>>>>>>> d176472f23174d073fb502384c981192b6be3cc4
Unmatched variable names in each year;


### Anticipated Timeline:

* November 11: Create project proposal and github repository
* November 12-19: Finalized project goal, datasets, divide responsibilities for each member
* November 20-26: Data cleaning and data visualization
* November 27- December 3: Data analyses and analysis report
* December 4-10: Finalize everything, create website
* December 11: Final project due
