---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(viridis)
library(shiny)
```

```{r data import}
cost_df = read.csv("data/insurance_medical_cost_personal_datasets.csv")

cost_df = cost_df %>% 
  mutate(
    smoker = ifelse(smoker == "yes", 1, 0),
    smoker = as.factor(smoker),
    sex = ifelse(sex == "male", 1, 2),
    sex = as.factor(sex),
    children = as.factor(children),
    age_group = case_when(age < 18 ~ 1, 
                          age >= 18 & age < 24 ~ 2,
                          age >= 25 & age < 44 ~ 3,
                          age >= 45 & age < 64 ~ 4,
                          age >= 65 ~ 5
                          ),
    age_group = as.factor(age_group),
    
    bmi_group = case_when(bmi < 20 ~ 1, 
                          bmi >= 20 & bmi < 30 ~ 2,
                          bmi >= 30 & bmi < 40 ~ 3,
                          bmi >= 40 & bmi < 50 ~ 4,
                          bmi >= 50 ~ 5
                          ),
    bmi_group = as.factor(bmi_group),
    
    children_group = ifelse(children == 0, 0, 1),
    children_group = as.factor(children_group)
     
    ) %>% 
    na.omit()

```

```{r build model}
cost_df_out = cost_df[-c(544,578, 1301),]
cost_df_log = cost_df_out %>% 
  mutate(
    Lncharges = log(charges)
  ) 
model_log = lm(Lncharges ~ smoker + children_group + age + bmi, data = cost_df_log) 
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
min_age = 
  cost_df %>% 
  distinct(age) %>% 
  min()

max_age = 
  cost_df %>% 
  distinct(age) %>% 
  max()
  
sliderInput(
  "age_choice",
  label = h3("Age"),
  min = min_age,
  max = 100,
  value = c(30)
)

min_bmi = 
  cost_df %>% 
  distinct(bmi) %>% 
  min()

max_bmi = 
  cost_df %>% 
  distinct(bmi) %>% 
  max()

sliderInput(
  "BMI_choice",
  label = h3("BMI"),
  min = min_bmi,
  max = max_bmi,
  value = c(20)
)
radioButtons(
  "smoke_or_not",
  label = h3("Smoke or not"),
  choices = c("Yes", "No"),
  selected = "Yes"
)
radioButtons(
  "have_kids_or_not",
  label = h3("Have kids or not"),
  choices = c("Yes", "No"),
  selected = "Yes"
)
```


Row {data-height = 500}
-----------------------------------------------------------------------

### Chart A

```{r}
renderPlotly({
predict_data = tibble(smoker = if_else(input[["smoke_or_not"]] == "Yes","1", "0"),
                      children_group = if_else(input[["have_kids_or_not"]] == "Yes", "1", "0"),
                      age = input[["age_choice"]],
                      bmi = input[["BMI_choice"]]
                      ) 

result = predict(model_log,predict_data,interval = "confidence") %>% 
  as_tibble() %>% 
  mutate(
    fit = exp(fit),
    lwr = exp(lwr),
    upr = exp(upr)
  ) %>% 
  mutate(x = "1") %>%
  ggplot(aes(fit,x)) + 
  geom_point(shape = 21, size = 3, fill = "white") +
  geom_errorbarh(aes(xmin = lwr, xmax = upr)) +
  xlim(0,60000) +
  geom_hline(yintercept = "1", size = 1.2) +
  labs(
    title = "Your recommended insurance charge $",
    x = "amount of charge $",
    y = "") 
ggplotly(result)
})
```


### Chart B

```{r}
renderPrint({
 predict_data = tibble(smoker = if_else(input[["smoke_or_not"]] == "Yes","1", "0"),
                      children_group = if_else(input[["have_kids_or_not"]] == "Yes", "1", "0"),
                      age = input[["age_choice"]],
                      bmi = input[["BMI_choice"]]
                      )

result = predict(model_log,predict_data,interval = "confidence") %>% 
  as_tibble() %>% 
  mutate(
    fit = exp(fit),
    lwr = exp(lwr),
    upr = exp(upr)
  )
fit_round = round(result$fit)
lwr_round = round(result$lwr)
upr_round = round(result$upr)

fit_out = paste("Your predicted insurance premium is $", fit_round)
ci_out = paste("Your recommended annal insurance premium range is $", lwr_round, "to $", upr_round)

cat(fit_out, ci_out, sep = "\n")

})
```

### Chart C

```{r}
renderPrint({
  predict_data = tibble(smoker = if_else(input[["smoke_or_not"]] == "Yes","1", "0"),
                      children_group = if_else(input[["have_kids_or_not"]] == "Yes", "1", "0"),
                      age = input[["age_choice"]],
                      bmi = input[["BMI_choice"]]
                      )

result = predict(model_log,predict_data,interval = "confidence") %>% 
  as_tibble() %>% 
  mutate(fit = exp(fit))

predict_data_smoker = tibble(smoker = "1",
                      children_group = if_else(input[["have_kids_or_not"]] == "Yes", "1", "0"),
                      age = input[["age_choice"]],
                      bmi = input[["BMI_choice"]]
                      ) 

smoker_result = predict(model_log,predict_data_smoker,interval = "confidence") %>% 
  as_tibble() %>% 
  mutate(fit = exp(fit))

predict_data_non_smoke = tibble(smoker = "0",
                      children_group = if_else(input[["have_kids_or_not"]] == "Yes", "1", "0"),
                      age = input[["age_choice"]],
                      bmi = input[["BMI_choice"]]
                      ) 

non_smoker_result = predict(model_log,predict_data_non_smoke,interval = "confidence") %>% 
  as_tibble() %>% 
  mutate(fit = exp(fit))

saved = round(smoker_result$fit - result$fit)
higher = round(result$fit - non_smoker_result$fit)

if (input[["smoke_or_not"]] == "No") cat("Congratulation! As a non-smoker, You saved $",saved, "for insurance premium than smoker")
if (input[["smoke_or_not"]] == "Yes") cat("As a smoker, Your insurance premium is $", higher,"higher than non-smoker")

})
```

